version: "3.9"
services:
  # Name of service
  dev:
    # same as docker build .
    build: .
    volumes:
      - ./:/src/NeuRPi
    env_file:
      - .env
    command: sleep infinity
    ports:
      - 10000-10010:10000-10010
