HARDWARE:
    Arduino:
        tag: 'List and properties of all arduinos required for session'
        num_arduinos: 1
        Primary:
            connection:
                port    : '/dev/ttyACM0'
                baudrate: None
                timeout : None
            tag: "[Lick, Reward]"

    GPIO:
        Stim_Onset:
            pin: None
            tag: 'TTL'

        Video_Monitor:
            pin: None
            tag: 'Frame Time'

    Display:
        tag: 'List and properties of all displays needed for session'
        num_screens: 1
        Primary:
            connection:
                port  : 0 
                window_size: (1920, 1080)
                refresh_rate : 30
                flags      : pygame.DOUBLEBUF | pygame.FULLSCREEN #| pygame.constants.SCALED 
                vsync      : True
                show_fps   : True


TASK:
    stimulus:
        _coherences:
            tag  : 'List of all coherences used in study'
            type : 'list'
            value: [100, 72, 36, 18, 9, 0]
        coherence_level:
            tag  : 'Level of difficulty for current block'
            type : 'int'
            value: 1
        repeats_per_block:
            tag  : 'Number of repeats of each coherences per block'
            type : 'int'
            value: 3

    bias:
        active_correction:
            tag             : 'Repeat threshold'
            type            : 'int'
            threshold       : 100
        passive_correction:
            tag             : 'Repeat threshold and window'
            type            : 'int'
            threshold       : 35
            rolling_window  : 10

    timings:
        fixation:
            tag             : 'Mean fixation time in secs'
            type            : 'int'
            value           : 1.00
        stimulus:
            tag             : 'Minimum and Maximum stimulus time in secs'
            type            : 'int'
            max_viewing     : 60.000
            min_viewing     : 0.3
        intertrial:
            tag             : 'Inter-trial interval in secs'
            type            : 'int'
            value            : 0.500

    feedback:
        correct:
            visual:
                tag  : 'Visual feedback for correct trial'
                type : 'tuple'
            audio :
                tag  : 'Audio feedback for correct trial'
                type : 'tuple'
            time  :
                tag  : 'Temporal delay feedback in secs'
                type : 'int'
                value: 0.500
            intertrial:
                tag  : 'Reaction Time dependent exponentially decaying intertrial_duration'
                base : 0
                power: 0
        incorrect:
            visual:
                tag  : 'Visual feedback for incorrect trial'
                type : 'tuple'
            audio :
                tag  : 'Audio feedback for incorrect trial'
                type : 'tuple'
            time  :
                tag  : 'Temporal delay feedback in secs'
                type : 'int'
                value: 1.500
            intertrial:
                tag  : 'Reaction Time dependent exponentially decaying intertrial_duration'
                base : 25
                power: -4
        invalid:
            visual:
                tag  : 'Visual feedback for invalid trial'
                type : 'tuple'
            audio :
                tag  : 'Audio feedback for invalid trial'
                type : 'tuple'
            time  :
                tag  : 'Temporal delay feedback in secs'
                type : 'int'
                value: 0
            intertrial:
                tag  : 'Reaction Time dependent exponentially decaying intertrial_duration'
                base : 0
                power: 0

    training_type:
        value: 1
        tag:
            0                  : 'Passive-Only'
            1                  : 'Active-Passive'
            2                  : 'Active-Only'
        active_passive:
            tag                : 'Parameters for Active-Passive Training (time in secs)'
            passive_rt_mu   : 10.000
            passive_rt_skew : 0.6
            passive_rt_sigma: 1.5
        graduation_direction:
            tag: 'Whether graduate is unidirectional i.e., only increasing difficulty (1) or bidirectional (0)'
            value: 0


STIMULUS:
    display:
        num_screens: 1
        screen     : 0 #0 
        window_size: [1920, 1080]
        frame_rate : 60
        flags      : pygame.DOUBLEBUF | pygame.FULLSCREEN #| pygame.constants.SCALED 
        vsync      : True
        show_fps   : True

    load_media:
        tag: 'Load media for visual and audio stimuli if any (relative to root directory)'
        value:
            images:
            videos:
            audios:
                fixation_tone:  'protocols/random_dot_motion/stimulus/audio/fixation_tone.wav'
                correct_tone :  'protocols/random_dot_motion/stimulus/audio/correct_tone.wav'
                incorrect_tone: 'protocols/random_dot_motion/stimulus/audio/incorrect_tone.wav'
                stimulus_tone:  'protocols/random_dot_motion/stimulus/audio/stimulus_tone.wav'
                
    required_functions:
        tag: 'List of all functions required for this phase. Please note that any color passed as a list will have to be converted to tuple for better performance.'
        value:
            initiate_fixation:
                stimulus_size  : [1920, 1080]
                background_color: [0,0,0]
                audio: fixation_tone       
            initiate_stimulus:
                stimulus_size  : [1920, 1080]
                background_color: [0,0,0]
                dots:
                    dot_radius      : 17
                    dot_color       : [255, 255, 255]
                    dot_fill        : 15
                    dot_vel         : 420
                    dot_lifetime    : 30
                audio: stimulus_tone
            update_stimulus:
            initiate_reinforcement:
                audio: 
                    correct: correct_tone
                    incorrect: incorrect_tone
                    invalid: incorrect_tone
            update_reinforcement:
            initiate_must_respond:
            update_must_respond:
            initiate_intertrial:
                background_color: [255,255,255] # [160,160,160]
            

    task_epochs:
        tag: 'List of all epochs and their respective functions
              Format:
                epoch_name:
                    init_func: function to initiate epoch. This will be executed once at the beginning of epoch.
                    update_func: function to update epoch. This will be executed continuously until epoch is over.'
        value:
            fixation_epoch:
                clear_queue: True
                init_func: initiate_fixation
                update_func:
            stimulus_epoch:
                clear_queue: True
                init_func: initiate_stimulus
                update_func: update_stimulus
            reinforcement_epoch:
                clear_queue: False
                init_func: initiate_reinforcement
                update_func: update_reinforcement
            must_respond_epoch:
                clear_queue: False
                init_func: initiate_must_respond
                update_func: update_must_respond
            intertrial_epoch:
                clear_queue: True
                init_func: initiate_intertrial
                update_func:



    courier_handle:
        tag:    'Instruction on how to handle few basic and other custom messages.
                Format: 
                    tag (str):  what each message mean, 
                    function (obj): which function to execute, 
                    visual:
                        need_update (bool): Need to update visual?
                        is_static (bool): Is update static or in loop with provided frame rate?
                        properties (dict): Optional parameters for update
                    audio:
                        need_update (bool): Need to update audio?
                        is_static (bool): Is update static or in loop?  
                        properties (dict): Optional parameters for update
                '

        fixation_epoch: 
            tag: 'Execution type for fixation window'
            function: initiate_fixation
            visual: 
                need_update: True
                is_static: True
                update_function: update_fixation
                properties:
                    load: 
                    generate:
                        background : (0,0,0)
            audio:
                need_update: True
                is_static: True
                update_function: 
                properties: 
                    load: ['protocols/random_dot_motion/stimulus/audio/fixation_tone.wav']
                    generate:

        stimulus_epoch: 
            tag: 'Execution type for stimulus window'
            function: initiate_stimulus
            visual: 
                need_update: True
                is_static: False
                update_function: update_stimulus
                properties:
                    load: 
                    generate:
                        stimulus_size  : (1920, 1080)
                        background : (0,0,0)
                        dots:
                            radius    : 17
                            color     : (255, 255, 255)
                            fill_prct : 15
                            velocity  : 420
                            lifetime  : 30
            audio:
                need_update: False
                is_static: False
                update_function: 
                properties: 
                    load: 
                    generate:

        response_epoch: 
            tag: 'Execution type for response window'
            function: initiate_response
            visual: 
                need_update: True
                is_static: True
                update_function: update_response
                properties:
                    load: 
                    generate: 
                        background : (0,0,0)
            audio:
                need_update: True
                is_static: True
                update_function: 
                properties:
                    load: 
                    generate:

        reinforcement_epoch: 
            tag: 'Execution type for reinforcement window'
            function: initiate_reinforcement
            visual: 
                need_update: False
                is_static: False
                update_function: update_reinforcement
                properties: 
                    load:
                    generate:
            audio:
                need_update: True
                is_static: True
                update_function: 
                properties:
                    load: 
                        correct         : ['protocols/random_dot_motion/stimulus/audio/correct_tone.wav']
                        incorrect       : ['protocols/random_dot_motion/stimulus/audio/incorrect_tone.wav']
                        invalid         : ['protocols/random_dot_motion/stimulus/audio/incorrect_tone.wav']
                    generate:

        must_respond_epoch: 
            tag: 'Execution type for must respond window'
            function: initiate_must_respond
            visual: 
                need_update: False
                is_static: False
                update_function: update_must_respond
                properties: 
                    load: 
                    generate:
            audio:
                need_update: False
                is_static: True
                update_function: 
                properties:
                    load: 
                    generate:

        intertrial_epoch:
            tag: 'Execution type for intertrial window'
            function: initiate_intertrial
            visual: 
                need_update: True
                is_static: True
                update_function: update_intertrial
                properties: 
                    load: 
                    generate:
                        background : (160,160,160)
            audio:
                need_update: False
                is_static: True
                update_function: 
                properties: 
                    load: 
                    generate:



EVENT_FILES: