
STIMULUS:
    display:
        num_screens: 1
        screen     : 0 #0 
        window_size: (1920, 1080)
        frame_rate : 60
        flags      : pygame.DOUBLEBUF | pygame.FULLSCREEN #| pygame.constants.SCALED 
        vsync      : True
        show_fps   : True

    courier_handle:
        tag:    'Instruction on how to handle few basic and other custom messages.
                Format: 
                    tag (str):  what each message mean, 
                    function (obj): which function to execute, 
                    visual:
                        need_update (bool): Need to update visual?
                        is_static (bool): Is update static or in loop with provided frame rate?
                        properties (dict): Optional parameters for update
                    audio:
                        need_update (bool): Need to update audio?
                        is_static (bool): Is update static or in loop?  
                        properties (dict): Optional parameters for update
                '

        initiate_fixation: 
            tag: 'Execution type for fixation window'
            function: initiate_fixation
            visual: 
                need_update: True
                is_static: True
                update_function: next_frame_fixation
                properties:
                    load: 
                    generate:
                        background : (0,0,0)
            audio:
                need_update: False
                is_static: True
                update_function: 
                properties: 
                    load: ['protocols/random_dot_motion/stimulus/audio/fixationTone.wav']
                    generate:

        initiate_stimulus: 
            tag: 'Execution type for stimulus window'
            function: initiate_stimulus
            visual: 
                need_update: True
                is_static: False
                update_function: next_frame_stimulus
                properties:
                    load: 
                    generate:
                        stimulus_size  : (1920, 1080)
                        background : (0,0,0)
                        dots:
                            radius    : 150
                            color     : (255, 255, 255)
                            fill_prct : 15
                            velocity  : 125
                            lifetime  : 30
            audio:
                need_update: False
                is_static: False
                update_function: 
                properties: 
                    load: 
                    generate:

        initiate_response: 
            tag: 'Execution type for response window'
            function: initiate_response
            visual: 
                need_update: True
                is_static: True
                update_function: next_frame_response
                properties:
                    load: 
                    generate: 
                        background : (0,0,0)
            audio:
                need_update: True
                is_static: True
                update_function: 
                properties:
                    load: 
                    generate:

        initiate_reinforcement: 
            tag: 'Execution type for reinforcement window'
            function: initiate_reinforcement
            visual: 
                need_update: False
                is_static: False
                update_function: next_frame_reinforcement
                properties: 
                    load:
                    generate:
            audio:
                need_update: True
                is_static: True
                update_function: 
                properties:
                    load: 
                        correct         : [] #'protocols/random_dot_motion/stimulus/audio/correctTone.wav']
                        incorrect       : ['protocols/random_dot_motion/stimulus/audio/incorrectTone.wav']
                        invalid         : [] #'protocols/random_dot_motion/stimulus/audio/incorrectTone.wav']
                    generate:

        initiate_must_respond: 
            tag: 'Execution type for must respond window'
            function: initiate_must_respond
            visual: 
                need_update: False
                is_static: False
                update_function: next_frame_must_respond
                properties: 
                    load: 
                    generate:
            audio:
                need_update: False
                is_static: True
                update_function: 
                properties:
                    load: 
                    generate:

        initiate_intertrial:
            tag: 'Execution type for intertrial window'
            function: initiate_intertrial
            visual: 
                need_update: False #True
                is_static: False #True
                update_function: next_frame_stimulus #next_frame_intertrial
                properties: 
                    load: 
                    generate:
                        background : #(160,160,160)
            audio:
                need_update: False
                is_static: True
                update_function: 
                properties: 
                    load: 
                    generate:

          








EVENT_FILES:
    events: 'event_all.txt'