HARDWARE:
    Arduino:
        Primary:
            connection:
                port    : "COM7"
                baudrate: None
                timeout : None
            tag: "[Lick, Reward]"

    GPIO:
        Stim_Onset:
            pin: None
            tag: 'TTL'

        Video_Monitor:
            pin: None
            tag: 'Frame Time'


TASK_PARAMETERS:
    stimulus:
        _coherences:
            tag  : 'List of all coherences used in study'
            type : 'list'
            value: [100, 72, 36, 18, 9, 0]
        coherence_level:
            tag  : 'Level of difficulty for current block'
            type : 'int'
            value: 1
        repeats_per_block:
            tag  : 'Number of repeats of each coherences per block'
            type : 'int'
            value: 3

    bias:
        active_correction:
            tag             : 'Repeat threshold'
            type            : 'int'
            threshold       : 100
        passive_correction:
            tag             : 'Repeat threshold and window'
            type            : 'int'
            threshold       : 100
            rolling_window  : 10

    timings:
        fixation:
            tag             : 'Mean fixation time in secs'
            type            : 'int'
            value           : 0.500
        stimulus:
            tag             : 'Minimum and Maximum stimulus time in secs'
            type            : 'int'
            max_viewing     : 60.000
            min_viewing     : 0.3
        intertrial:
            tag             : 'Inter-trial interval in secs'
            type            : 'int'
            mean            : 0.500

    feedback:
        correct:
            visual:
                tag  : 'Visual feedback for correct trial'
                type : 'tuple'
            audio :
                tag  : 'Audio feedback for correct trial'
                type : 'tuple'
            time  :
                tag  : 'Temporal delay feedback in secs'
                type : 'int'
                value: 0.500
            intertrial:
                tag  : 'Reaction Time dependent exponentially decaying intertrial_duration'
                base : 0
                power: 0
        incorrect:
            visual:
                tag  : 'Visual feedback for correct trial'
                type : 'tuple'
            audio :
                tag  : 'Audio feedback for correct trial'
                type : 'tuple'
            time  :
                tag  : 'Temporal delay feedback in secs'
                type : 'int'
                value: 1.000
            intertrial:
                tag  : 'Reaction Time dependent exponentially decaying intertrial_duration'
                base : 25
                power: -4
        noresponse:
            visual:
                tag  : 'Visual feedback for correct trial'
                type : 'tuple'
            audio :
                tag  : 'Audio feedback for correct trial'
                type : 'tuple'
            time  :
                tag  : 'Temporal delay feedback in secs'
                type : 'int'
                value: 0
            intertrial:
                tag  : 'Reaction Time dependent exponentially decaying intertrial_duration'
                base : 25
                power: -4

    training_type:
        value: 1
        tag:
            0                  : 'Passive-Only'
            1                  : 'Active-Passive'
            2                  : 'Active-Only'
        active_passive:
            tag                : 'Parameters for Active-Passive Training (time in secs)'
            passive_rt_mu   : 60.000
            passive_rt_sigma: 0.6



STIMULUS:
    display:
        num_screens: 1
        screen     : 1#0 
        window_size: (1920, 1280)
        frame_rate : 60
        flags      : pygame.DOUBLEBUF | pygame.FULLSCREEN
        vsync      : 0

    # source_paths:
    #     tag: 'Source path for all audio-video stimulus, if needed'
    #     type: list
    #     video: False
    #     audio:
    #         fixation_onset   : [fixationTone.wav] # '/NeuRPi/stimulus/fixationTone.wav'
    #         stimulus_onset   : False
    #         reinforcement_onset:
    #             correct         : [correctTone.wav] # '/NeuRPi/stimulus/correctTone.wav'
    #             incorrect       : [incorrectTone.wav] # '/NeuRPi/stimulus/incorrectTone.wav'
    #             invalid         : [incorrectTone.wav] # '/NeuRPi/stimulus/incorrectTone.wav'
    #         intertrial_onset : False

    courier_handle:
        tag:    'Instruction on how to handle few basic and other custom messages.
                Format: 
                    tag (str):  what each message mean, 
                    function (obj): which function to execute, 
                    visual:
                        need_update (bool): Need to update visual?
                        is_static (bool): Is update static or in loop with provided frame rate?
                        properties (dict): Optional parameters for update
                    audio:
                        need_update (bool): Need to update audio?
                        is_static (bool): Is update static or in loop?  
                        properties (dict): Optional parameters for update
                '

        initiate_fixation: 
            tag: 'Execution type for fixation window'
            function: fixation
            visual: 
                need_update: True
                is_static: True
                properties:
                    load: 
                    generate:
                        background : (0,0,0)
            audio:
                need_update: True
                is_static: True
                properties: 
                    load: [fixationTone.wav] # '/NeuRPi/stimulus/fixationTone.wav'
                    generate:

        initiate_stimulus: 
            tag: 'Execution type for stimulus window'
            function: stimulus
            visual: 
                need_update: True
                is_static: True
                properties:
                    load: 
                    generate:
                        stim_size  : (1920, 1280)
                        background : (0,0,0)
                        dots:
                            radius    : 15
                            color     : (255, 255, 255)
                            fill_prct : 15
                            velocity  : 150
                            lifetime  : 30
            audio:
                need_update: False
                is_static: True
                properties: 
                    load: 
                    generate:

        initiate_response: 
            tag: 'Execution type for response window'
            function: response
            visual: 
                need_update: True
                is_static: True
                properties:
                    load: 
                    generate: 
                        background : (0,0,0)
            audio:
                need_update: True
                is_static: True
                properties:
                    load: 
                    generate:

        initiate_reinforcement: 
            tag: 'Execution type for reinforcement window'
            function: reinforcement
            visual: 
                need_update: False
                is_static: True
                properties: 
                    load:
                    generate:
            audio:
                need_update: True
                is_static: True
                properties:
                    load: 
                        correct         : [correctTone.wav] # '/NeuRPi/stimulus/correctTone.wav'
                        incorrect       : [incorrectTone.wav] # '/NeuRPi/stimulus/incorrectTone.wav'
                        invalid         : [incorrectTone.wav] # '/NeuRPi/stimulus/incorrectTone.wav'
                    generate:

        initiate_must_response: 
            tag: 'Execution type for must respond window'
            function: must_respond
            visual: 
                need_update: False
                is_static: True
                properties: 
                    load: 
                    generate:
            audio:
                need_update: False
                is_static: True
                properties:
                    load: 
                    generate:

        initiate_intertrial:
            tag: 'Execution type for intertrial window'
            function: intertrial
            visual: 
                need_update: True
                is_static: True
                properties: 
                    load: 
                    generate:
                        background : (50,50,50)
            audio:
                need_update: False
                is_static: True
                properties: 
                    load: 
                    generate:

          








EVENT_FILES:
    events: 'event_all.txt'