
# ============================================================================
# DIRECTORY PATHS
# ============================================================================
# DUPLICATE 1 - Original paths
DATADIR: /home/pi1/temp_data/
DATADIR: 'C:/Users/Trach_McGee/Desktop/Data/'
BASEDIR: 'C:/Users/Trach_McGee/Desktop/NeuRPi/'
BASEDIR: NeuRPi/
PROTOCOLDIR: protocols/
VENVDIR: venv/
LOGDIR: logs/

# DUPLICATE 2 - Alternative paths with comments
# Path for data directory. Intentionally kept in another directory to avoid accidental deletion
# Path relative to home

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
# DUPLICATE 1 - Original logging settings
LOGLEVEL: DEBUG
LOGSIZE: 5000000.0
LOGNUM: 4

# ============================================================================
# SYSTEM IDENTIFICATION
# ============================================================================
# DUPLICATE 1 - Original system name
NAME: rig_1

# DUPLICATE 2 - Alternative system name
NAME: T

# ============================================================================
# NETWORK CONFIGURATION
# ============================================================================
# DUPLICATE 1 - Original network settings
MSGPORT: 11001
TERMINALIP: 10.155.204.229
PUSHPORT: 11000

# DUPLICATE 2 - Alternative network settings
MSGPORT: 11000
TERMINALIP: 10.155.204.229
PUSHPORT: 11000

# ============================================================================
# LINEAGE/HIERARCHY CONFIGURATION
# ============================================================================
LINEAGE: NONE
CHILDID: NONE
PARENTID: NONE
PARENTIP: NONE
PARENTPORT: NONE

# ============================================================================
# SYSTEM PERFORMANCE
# ============================================================================
PING_INTERVAL: 5
DRAWFPS: 20

# ============================================================================
# HARDWARE CONFIGURATION
# ============================================================================
HARDWARE:
  Arduino:
    Primary:
      tag: '[Lick, Reward]'
      connection:
        port: /dev/ttyUSB0
        baudrate: 115200
        timeout: false
      reward:
        calibration: 56
        calibration_left: 85
        calibration_right: 83
      lick:
        threshold: 1.5
        threshold_left: 9.0
        threshold_right: 16.0
        slope: 0
  GPIO:
    Stim_Onset:
      pin: None
      tag: TTL
    Video_Monitor:
      pin: None
      tag: Frame Time
  Display:
    tag: Screens and their properties connected to rig
    vsync: true
    port: 0
    window_size:
    - 1280
    - 720
    max_fps: 60
    flags:
    - FULLSCREEN
    - DOUBLEBUF
    - NOFRAME
    - constants.SCALED
    - HWSURFACE
    mouse_visible: false
    font:
    - Arial
    - 20
