# Path relative to home
BASEDIR: Desktop/NeuRPi/
# Path relative to package
PROTOCOLDIR: protocols/
VENVDIR: venv/
DATADIR: data/
LOGDIR:  logs/

LOGLEVEL: DEBUG  # Choices [DEBUG, INFO, WARNING, ERROR]
LOGSIZE: 5000000.0
LOGNUM: 4

NAME: rig_4
MSGPORT: 10001
TERMINALIP: 10.155.206.212
PUSHPORT: 10000

LINEAGE: NONE # Choices [NONE, PARENT, CHILD]
CHILDID: NONE
PARENTID: NONE
PARENTIP: NONE
PARENTPORT: NONE
PING_INTERVAL: 5
DRAWFPS: 20