BASEDIR: NeuRPi/
PROTOCOLDIR: protocols/
VENVDIR: venv/
DATADIR: data/
LOGDIR: logs/
LOGLEVEL: DEBUG
LOGSIZE: 5000000.0
LOGNUM: 4
NAME: rig_1
MSGPORT: 11001
TERMINALIP: 10.155.206.212
PUSHPORT: 11000
LINEAGE: NONE
CHILDID: NONE
PARENTID: NONE
PARENTIP: NONE
PARENTPORT: NONE
PING_INTERVAL: 5
DRAWFPS: 20
HARDWARE:
  Arduino:
    Primary:
      tag: '[Lick, Reward]'
      connection:
        port: /dev/ttyACM0
        baudrate: 9600
        timeout: false
      reward:
        caliberation: 30
      lick:
        threshold: 4
        slope: 20
  GPIO:
    Stim_Onset:
      pin: None
      tag: TTL
    Video_Monitor:
      pin: None
      tag: Frame Time
