DATADIR: Y:/
BASEDIR: D:/PROJECT/research/NeuRPi/
PROTOCOLDIR: protocols/
VENVDIR: .venv/
LOGDIR: logs/
LOGLEVEL: WARNING
LOGSIZE: 5000000.0
LOGNUM: 4
NAME: T
MSGPORT: 12000
TERMINALIP: 10.155.205.212
PUSHPORT: 12000
LINEAGE: NONE
CHILDID: NONE
PARENTID: NONE
PARENTIP: NONE
PARENTPORT: NONE
PING_INTERVAL: 5
DRAWFPS: 20
