DATADIR: C:/Users/Trach_McGee/Desktop/Data/
BASEDIR: C:/Users/Trach_McGee/Documents/NeuRPi/
PROTOCOLDIR: protocols/
VENVDIR: .venv/
LOGDIR: logs/
LOGLEVEL: WARNING
LOGSIZE: 5000000.0
LOGNUM: 4
NAME: T
MSGPORT: 11000
TERMINALIP: 10.155.204.229
PUSHPORT: 11000
LINEAGE: NONE
CHILDID: NONE
PARENTID: NONE
PARENTIP: NONE
PARENTPORT: NONE
PING_INTERVAL: 5
DRAWFPS: 20
