NAME:
  type: str
  text: 'Agent Name:'
  default: rig_4
  scope: Scopes.COMMON
PUSHPORT:
  type: int
  text: 'Push Port - Router port used by the Terminal or upstream agent:'
  default: 10000
  scope: Scopes.COMMON
MSGPORT:
  type: int
  text: 'Message Port - Router port used by this agent to receive messages:'
  default: 10001
  scope: Scopes.COMMON
TERMINALIP:
  type: str
  text: 'Terminal IP:'
  default: 10.155.206.212
  scope: Scopes.COMMON
LOGLEVEL:
  type: choice
  text: 'Log Level:'
  choices:
  - DEBUG
  - INFO
  - WARNING
  - ERROR
  default: WARNING
  scope: Scopes.COMMON
LOGSIZE:
  type: int
  text: Size of individual log file (in bytes)
  default: 5000000.0
  scope: Scopes.COMMON
LOGNUM:
  type: int
  text: Number of logging backups to keep of LOGSIZE
  default: 4
  scope: Scopes.COMMON
LINEAGE:
  type: choice
  text: Are we a parent or a child?
  choices:
  - NONE
  - PARENT
  - CHILD
  default: NONE
  scope: Scopes.LINEAGE
CHILDID:
  type: list
  text: 'List of Child ID:'
  default: []
  depends:
  - LINEAGE
  - PARENT
  scope: Scopes.LINEAGE
PARENTID:
  type: str
  text: 'Parent ID:'
  default: NONE
  depends:
  - LINEAGE
  - CHILD
  scope: Scopes.LINEAGE
PARENTIP:
  type: str
  text: 'Parent IP:'
  default: NONE
  depends:
  - LINEAGE
  - CHILD
  scope: Scopes.LINEAGE
PARENTPORT:
  type: str
  text: 'Parent Port:'
  default: NONE
  depends:
  - LINEAGE
  - CHILD
  scope: Scopes.LINEAGE
PING_INTERVAL:
  type: float
  text: How many seconds should pilots wait in between pinging the Terminal?
  default: 5
  scope: Scopes.PILOT
DRAWFPS:
  type: int
  text: FPS to draw videos displayed during acquisition
  default: 20
  scope: Scopes.TERMINAL
