VENVDIR: /src/NeuRPi/venv
BASEDIR: /src/NeuRPi/
DATADIR: /src/NeuRPi/data/
LOGDIR:  /src/NeuRPi/data/logs/
PROTOCOLDIR: /src/NeuRPi/protocols/

LOGLEVEL: DEBUG  # Choices [DEBUG, INFO, WARNING, ERROR]
LOGSIZE: 5000000.0
LOGNUM: 4

NAME: rig_4
MSGPORT: 10001
TERMINALIP: 10.155.206.212
PUSHPORT: 10000

LINEAGE: NONE # Choices [NONE, PARENT, CHILD]
CHILDID: NONE
PARENTID: NONE
PARENTIP: NONE
PARENTPORT: NONE
PING_INTERVAL: 5
DRAWFPS: 20