BASEDIR: NeuRPi/
PROTOCOLDIR: protocols/
VENVDIR: .venv/
DATADIR: /home/pi1/temp_data/
LOGDIR: logs/
LOGLEVEL: DEBUG
LOGSIZE: 5000000.0
LOGNUM: 4
NAME: rig_1
MSGPORT: 12001
CONTROLLERIP: 10.155.204.229
PUSHPORT: 12000
LINEAGE: NONE
CHILDID: NONE
PARENTID: NONE
PARENTIP: NONE
PARENTPORT: NONE
PING_INTERVAL: 5
DRAWFPS: 20
HARDWARE:
  Arduino:
    Primary:
      tag: '[Lick, Reward]'
      connection:
        port: /dev/ttyUSB0
        baudrate: 115200
        timeout: false
      reward:
        calibration: 56
        calibration_left: 85
        calibration_right: 83
      lick:
        threshold: 1.5
        threshold_left: 9.0
        threshold_right: 16.0
        slope: 0
  GPIO:
    Stim_Onset:
      pin: None
      tag: TTL
    Video_Monitor:
      pin: None
      tag: Frame Time
  Display:
    tag: Screens and their properties connected to rig
    vsync: true
    port: 0
    window_size:
    - 1280
    - 720
    max_fps: 60
    flags:
    - FULLSCREEN
    - DOUBLEBUF
    - NOFRAME
    - constants.SCALED
    - HWSURFACE
    mouse_visible: false
    font:
    - Arial
    - 20
